import React from 'react';
import Header from '../components/Header';
import Head from 'next/head';
import { NextComponentType } from 'next';

type AppLayoutProps = {
  children: React.ReactNode;
};

const Layout = ({ children }: AppLayoutProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <div>{children}</div>
      <footer>footer</footer>
    </>
  );
};

export default Layout;
